select * from customers
--1.What is the total revenue generated by males vs female customers
select SUM(purchase_amount)as total_revenue ,gender
from customers
group by gender

--2.which customers used a discount but still spent more than avg  purchase amount
select customer_id,purchase_amount
from customers
where discount_applied = 'Yes' AND purchase_amount >=(select AVG(purchase_amount)from customers)

--3.which are the top 5  products with the highest average review rating
select TOP 5 item_purchased,ROUND(AVG(review_rating),2)as avg_review
from customers
group by item_purchased
ORDER BY AVG(review_rating)DESC

--4.Compare the average purchase amount between standard and express shipping
select  avg(purchase_amount)as avg_purchase_amount, shipping_type
from customers
where shipping_type in ('standard' ,'Express')
group by shipping_type

--5.Do subsribed customers spend more ? compared average spend and total revenue
--between subscribers and non_subscribers
select  subscription_status,ROUND(AVG(purchase_amount),2)as average_spend,SUM(purchase_amount)as total_revenue
,COUNT(customer_id)AS no_of_customers
from customers
group by subscription_status
--6. which 5 products have the highest percentage of purchase with discount applied
select  TOP 5 item_purchased,
        100 *SUM(CASE WHEN discount_applied ='yes' THEN 1 ELSE 0 END)/COUNT (*)AS discount_rate
from customers
group by item_purchased
order by 100 *SUM(CASE WHEN discount_applied ='yes' THEN 1 ELSE 0 END)/COUNT (*) DESC

--7. Sergement customers into New , Returning , and loyal customers based on the total number of previous purchases
--and show the count of each seggement
WITH CTE AS(
select  customer_id,previous_purchases,
     CASE
	 WHEN previous_purchases = 1 THEN  'NEW'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	 ELSE 'LOYAL'
	 END AS Customer_sergement
from customers
)
SELECT COUNT(*)as total_count,Customer_sergement FROM CTE
GROUP BY Customer_sergement
order by COUNT(*) desc

--8--which top 3 products are most purchased within each category
WITH ITEM_COUNT AS(
select count(customer_id)as total_count,
item_purchased,category,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) desc)as item_rank
from customers
group by item_purchased,category
)
SELECT item_rank,category,item_purchased,total_count
from ITEM_COUNT
where item_rank <=3

--Are customers who are repeat buyres more than 5 previuos purchases also likely to subscribe
select Count(customer_id)as repeat_buyes,subscription_status
from customers
where previous_purchases >5
group by subscription_status

--revenue contribution of each age group
select age_group,SUM(purchase_amount)AS Revenue
from customers
group by age_group
order by SUM(purchase_amount)desc